### ISSUE TITLE
Only allows wsfed protocol with idpMetaUrl

### ISSUE THREAD

**Issue by dpetebrown** [mcguinness/saml-sp#8]
When using idpMetaUrl. The protocol says wsfed. When using saml tracer it verifies that it is using wsfed. I need saml. I tried using the --protocol samlp but it still says wsfed.

**Comment by mcguinness** [comment]
Does your metadata publish both WSFED and SAMLP service descriptions but the SP is not honoring the protocol selection from the CLI argument?

**Comment by dpetebrown** [comment]
Karl,
That could be the problem. I don't think my metadata supports both wsfed
and samlp just samlp. But the output says wsfed for protocol after parsing
the metadata. The unable to parse error after the metadata is loaded. It
shows the data as loaded and then throws the error. I change our urls to
hide our site and truncated the certs. Was not sure if this data gets
posted to Github for all to see. When you look in saml tracer for firefox
it shows the payload as wsfed and not saml.

C:\samplesaml\saml-sp-master>node bin/server.js --idpMetaUrl
https://notrealnameofsite.com/idp/metadata --protocol samlp

parsing arguments...
resolving path C:\samplesaml\saml-sp-master\config\sp-cert.pem
resolving path C:\samplesaml\saml-sp-master\config\sp-key.pem
downloading IdP metadata from https:// notrealnameofsite.com /idp/metadata

<md:EntityDescriptor xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata"
xmlns:dsig="http://www.w3.org/2000/09/xmldsig#" xmlns:enc="
http://www.w3.org/2001/04/xmlenc#"
xmlns:mdattr="urn:oasis:names:tc:SAML:metada


unable to parse RoleDescriptor metadata TypeError: Cannot read property
'PassiveRequestorEndpoint' of undefined
    at parser.parseString
(C:\samplesaml\saml-sp-master\lib\idp-metadata.js:102:47)
    at Parser.<anonymous>
(C:\samplesaml\saml-sp-master\node_modules\xml2js\lib\parser.js:303:18)
    at Parser.emit (events.js:182:13)
    at SAXParser.onclosetag
(C:\samplesaml\saml-sp-master\node_modules\xml2js\lib\parser.js:261:26)
    at emit
(C:\samplesaml\saml-sp-master\node_modules\sax\lib\sax.js:624:35)
    at emitNode
(C:\samplesaml\saml-sp-master\node_modules\sax\lib\sax.js:629:5)
    at closeTag
(C:\samplesaml\saml-sp-master\node_modules\sax\lib\sax.js:889:7)
    at SAXParser.write
(C:\samplesaml\saml-sp-master\node_modules\sax\lib\sax.js:1436:13)
    at Parser.exports.Parser.Parser.parseString
(C:\samplesaml\saml-sp-master\node_modules\xml2js\lib\parser.js:322:31)
    at Parser.parseString
(C:\samplesaml\saml-sp-master\node_modules\xml2js\lib\parser.js:5:59)

[Configuration]
 { _: [],
  version: false,
  signAuthnRequests: true,
  signed: true,
  requestNameIDFormat: true,
  validateNameIDFormat: true,
  requestAuthnContext: true,
  https: false,
  help: false,
  idpMetaUrl: 'https://notrealnameofsite.com /idp/metadata',
  protocol: 'wsfed',
  port: 7070,
  p: 7070,
  idpIssuer: 'urn:example:idp',
  iss: 'urn:example:idp',
  idpSsoBinding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
  idpSloBinding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
  audience: 'urn:example:sp',
  aud: 'urn:example:sp',
  providerName: 'Simple SAML Service Provider',
  acsUrls: [ '/saml/sso' ],
  signatureAlgorithm: 'rsa-sha256',
  digestAlgorithm: 'sha256',
  nameIDFormat: 'urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress',
  nameid: 'urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress',
  authnContextClassRef:
   'urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport',
  acr:
   'urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport',
  spCert:
   '-----BEGIN
CERTIFICATE-----\nMI6+wzcQVhSOlMk2tXR+fIKQExFrO\nuK9tbX3JIBUqItpI+HnAow509CnM134svw8PTFLkR6/CcMqnDfDK1m993PyoC1Y+\nN4X9XkhSmEQoAlAHPI5LHrvuujM13nvtoVYvKYoj7ScgumkpWNEvX652LfXOnKYl\nkB8ZybuxmFfIkzedQrbJsyOhfL03cMECAwEAATANBgkqhkiG9w0BAQUFAAOCAQEA\neHwzqwnzGEkxjzSD47imXaTqtYyETZow7XwBc0ZaFS50qRFJUgKTAmKS1xQBP/qH\npStsROT35DUxJAE6NY1Kbq3ZbCuhGoSlY0L7VzVT5tpu4EY8+Dq/u2EjRmmhoL7U\nkskvIZ2n1DdERtd+YUMTeqYl9co43csZwDno/IKomeN5qaPc39IZjikJ+nUC6kPF\nKeu/3j9rgHNlRtocI6S1FdtFz9OZMQlpr0JbUt2T3xS/YoQJn6coDmJL5GTiiKM6\ncOe+Ur1VwzS1JEDbSS2TWWhzq8ojLdrotYLGd9JOsoQhElmz+tMfCFQUFLExinPA\nyy7YHlSiVX13QH2XTu/iQQ==\n-----END
CERTIFICATE-----\n',
  spKey:
   '-----BEGIN RSA PRIVATE KEY-----\nMIIEpWg==\n-----END RSA PRIVATE
KEY-----\n',
  spSsoBinding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST',
  '$0': 'bin\\server.js',
  settings: undefined,
  idpSsoUrl: 'https://notrealnameofsite.com/idp/samlv20',
  idpSloUrl: undefined,
  idpCert:
   '-----BEGIN
CERTIFICATE-----\nMIIG4DCCBcigAwIBAgIQYsWIXPkObgpk6kWIlIrrszANBgkqhkiG9w0BAQsFADBB\nMQswCQYDVQQGEwJVUzEVMBMGA1UEChMMdGhhd3RlLCBJbmMuMRswGQgU\n-----END
CERTIFICATE-----\n',
  idpThumbprint: undefined,
  httpsPrivateKey: undefined,
  httpsCert: undefined,
  relayState: undefined }


starting server...

        http://localhost:7070

Protocol: WS-Federation

IdP Issuer URI:
        urn:example:idp
IdP SSO ACS URL:
        https://notrealnameofsite.com/idp/samlv20

RP Issuer URI:
        urn:example:sp
RP Audience URI:
        urn:example:sp
RP Security Token Response URL:
        /saml/sso
RP Default Context:
        undefined

**Comment by mcguinness** [comment]
Can you post the metadata?

**Comment by dpetebrown** [comment]
Do you need to know the actual urls in the metadata or can I hide them?

**Comment by mcguinness** [comment]
Nope you can replace the domain

**Comment by dpetebrown** [comment]
Thanks for your help Karl. For now, I will close the issue. Not sure I can
scrub the data clean enough.
